
// This file has been generated by the GUI designer. Do not modify.
namespace ProcessMonitor
{
	public partial class PageProcessOverview
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.VBox vbox1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView txtSummary;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TreeView nvProcessList;
		private global::Gtk.Statusbar sbMain;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ProcessMonitor.PageProcessOverview
			global::Stetic.BinContainer.Attach (this);
			this.WidthRequest = 596;
			this.HeightRequest = 446;
			this.Name = "ProcessMonitor.PageProcessOverview";
			// Container child ProcessMonitor.PageProcessOverview.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.txtSummary = new global::Gtk.TextView ();
			this.txtSummary.Buffer.Text = "Process Overview Summary";
			this.txtSummary.HeightRequest = 134;
			this.txtSummary.CanFocus = true;
			this.txtSummary.Name = "txtSummary";
			this.txtSummary.Editable = false;
			this.GtkScrolledWindow1.Add (this.txtSummary);
			this.vbox1.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow1]));
			w3.Position = 0;
			w3.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.nvProcessList = new global::Gtk.TreeView ();
			this.nvProcessList.CanFocus = true;
			this.nvProcessList.Name = "nvProcessList";
			this.GtkScrolledWindow2.Add (this.nvProcessList);
			this.vbox1.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow2]));
			w5.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.sbMain = new global::Gtk.Statusbar ();
			this.sbMain.Name = "sbMain";
			this.sbMain.Spacing = 6;
			this.vbox1.Add (this.sbMain);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.sbMain]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			w1.Add (this.vbox1);
			this.GtkScrolledWindow.Add (w1);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
